name: nobelGPT
channels:
  - pytorch
  - defaults
dependencies:
  - numpy=1.26.4
  - pip=24.0
  - python=3.11.9
  - pytorch
  - torchaudio
  - torchvision
  - pip:
      - jupyter==1.0.0
      - pre-commit==3.7.1
      - pytest==8.3.1
      - lightning==2.3.3
      - tokenizers==0.19.1
