name: nobelGPT
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - numpy=1.26.4
  - pip=24.0
  - python=3.11.9
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - torchaudio=2.4.0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - pip:
      - jupyter==1.0.0
      - pre-commit==3.7.1
      - pytest==8.3.1
      - lightning==2.3.3
      - tokenizers==0.19.1
      - shortuuid
      - tqdm
      - tensorboardX
      - crc32c
